language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: nzdlufo
  api_key:
    secure: XPOaNZ8t6P15oGqH9crWBLrAbZf+PhJEEH2O5Misg4kZhuQhR3fftLEeu2Pou6e1oLwnhyF1xNELcrW4m6vO56adIrurFQHhyJBfVf0TgJ1zp5ARgUID5McH7BZSJwpT/DqWoNdXBjI0rFi/aAK09nWV4M0sbMhi9SunmxE0SjX9gPNd1eeXJKrGjz0oYHxvWDdoE6h6tf3vYXVZClQ/RKbWmkWi4p9/t8dzPq3lR0LTkOYI+SEhS6BKondCr0oJxfmZJe9wyvd3MvXecqQrJXVS/vLUo6y0p48CQaeM3NVNm6xYIuRbUOUdThehlnbJq1ukTcalDSiK8IAsW6W+sPDP0ADZMuIKY6cv1QdC6FI+Bx35xzYopHxKPlwp/SWUlm8FWHe5FjS+KIqWNpE6vlBvlj1DxnCfX5eHkfs1zqzzuRGH0uukJtQ/U3dRT9gdHalTO8pg13e1nvmwD++kHGWeZ5abzjw9UEx6AyaT9Iic0MHZGOY0u+5Nimza4udVx42hfWxM4kQHVRQ6NW9Y1FiF7KUbmzwf5a8ao2RGjvHdFu2ehZTS2wj+TYKZqoAXllt5Zmd8yyq/903L20P61iKVIqLxqIVfXkATfO8vGtQvLTICn0HqsyEkeAXD27S+cQYdpgGFuvwZ+8mwlD4mCkYW0WM+VDcHk18WQLFf1TQ=
