language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  app: nzdlufo
  api_key:
    secure: vUBitxBJhfvrLk6zelsMyLVa0RK7pJfE9cBUV5+Axu3xHhhH070qhKsmDvgvSCubbgd8ZyIkKbtdYMhrB9vM8YOcLJibP9meKQ9zBrN3MAEGdgOwbGy/Z4i/JU+hCJpNdSKVJ8a/IqtVDjT505bfdNID0cLUTlCpCT/Xl9wTKio8q5q3nBQ+g/sF013VsG+Jnfd+ll3TrFgh17OjMZ/cu3hPfB/ycEIRW0nq7LCsTWAd9BkeATtEUkStrJRu4ECN8NpqT05/OaiQLZun8qCKXW8RnFBpfKU3QtDhrPuO7+QW1HwtHWGsN7E9BMQUc5v59zPvnAb/ALHIMhBK1/1Az9UYbhPcS7OQcPP14SWWLO/k/Q/7c4ub00HaqRBIZ+iPPW1DTloD/MmiYLwSArOkA7vil6IfbQsWjlGHmNTOBjeIKsHKaDGImpXGS1WSUATtZUNypGPJf/J+PcOhglIs+N3CmTr+B5gc7YOXmHElkn1Oym61F1qgTOcr8Ov5zhQfHyXdvpSmgbYws+KP8VY5LoDQRqQnOkGVoe8zARVaNt7HSDOUOnFxabjYnGIsLsnwv/n1aH2WRYGBB36sFle2cJeiypOjTHdgwR2OFTFrbHOixhIMJ8pcVP3Isd3KQNQYeUameZKjAgdbItIBE4T259AMJWRmSjg4VJLoFOA/7Eg=
